import { z } from "zod";

/** Placeholder schema — business validations come in later phases. */
export const healthResponseSchema = z.object({
  status: z.literal("ok"),
});

export type HealthResponse = z.infer<typeof healthResponseSchema>;

export {
  emailSchema,
  forgotPasswordSchema,
  loginSchema,
  passwordSchema,
  resetPasswordSchema,
  signupSchema,
  type ForgotPasswordInput,
  type LoginInput,
  type ResetPasswordInput,
  type SignupInput,
} from "@/lib/validations/auth";

export {
  CURRENCIES,
  LOGO_ALLOWED_MIME_TYPES,
  LOGO_MAX_BYTES,
  TIMEZONES,
  currencySchema,
  isAllowedLogoMimeType,
  isValidTimezone,
  normalizeWebsite,
  phoneSchema,
  restaurantFormSchema,
  restaurantOnboardingSchema,
  restaurantUpdateSchema,
  slugSchema,
  timezoneSchema,
  toRestaurantPayload,
  websiteSchema,
  type CurrencyCode,
  type RestaurantFormValues,
  type RestaurantOnboardingInput,
  type RestaurantUpdateInput,
} from "@/lib/validations/restaurant";

export {
  branchFieldsSchema,
  BRANCH_PAGE_SIZE_OPTIONS,
  BRANCH_SORT_FIELDS,
  DEFAULT_BRANCH_PAGE_SIZE,
  branchListQuerySchema,
  createBranchSchema,
  parseBranchListQuery,
  setBranchStatusSchema,
  toBranchPayload,
  updateBranchSchema,
  type BranchFormValues,
  type BranchListQuery,
  type BranchSortField,
  type CreateBranchInput,
  type SetBranchStatusInput,
  type UpdateBranchInput,
} from "@/lib/validations/branch";

export {
  customerExperienceSchema,
  customerExperienceUpdateSchema,
  generalSettingsSchema,
  generalSettingsUpdateSchema,
  localeSettingsSchema,
  queueSettingsSchema,
  queueSettingsUpdateSchema,
  tokenPrefixSchema,
  type CustomerExperienceUpdateInput,
  type CustomerExperienceValues,
  type GeneralSettingsUpdateInput,
  type GeneralSettingsValues,
  type LocaleSettingsValues,
  type QueueSettingsUpdateInput,
  type QueueSettingsValues,
} from "@/lib/validations/settings";

export {
  clearBranchHoursSchema,
  createSpecialHoursSchema,
  dayScheduleSchema,
  deleteSpecialHoursSchema,
  operatingPeriodSchema,
  specialHoursFieldsSchema,
  updateOperatingHoursSchema,
  updateSpecialHoursSchema,
  weekScheduleSchema,
  type ClearBranchHoursInput,
  type CreateSpecialHoursInput,
  type DeleteSpecialHoursInput,
  type OperatingPeriodInput,
  type SpecialHoursFields,
  type UpdateOperatingHoursInput,
  type UpdateSpecialHoursInput,
  type WeekScheduleValues,
} from "@/lib/validations/hours";

export {
  COMMON_TABLE_CAPACITIES,
  TABLE_SORT_FIELDS,
  TABLE_STATUSES,
  TABLE_STATUS_LABELS,
  createTableSchema,
  createTableSectionSchema,
  deleteTableSchema,
  deleteTableSectionSchema,
  reorderTableSectionsSchema,
  sectionNameSchema,
  tableCapacitySchema,
  tableFieldsSchema,
  tableNumberSchema,
  tableStatusSchema,
  toTableWritePayload,
  updateTableSchema,
  updateTableSectionSchema,
  updateTableStatusSchema,
  type CreateTableInput,
  type CreateTableSectionInput,
  type DeleteTableInput,
  type DeleteTableSectionInput,
  type ReorderTableSectionsInput,
  type TableFormValues,
  type TableSortField,
  type TableStatus,
  type UpdateTableInput,
  type UpdateTableSectionInput,
  type UpdateTableStatusInput,
} from "@/lib/validations/table";

export {
  CUSTOMER_NAME_MAX,
  CUSTOMER_PAGE_SIZE_OPTIONS,
  CUSTOMER_STAT_FILTERS,
  DEFAULT_CUSTOMER_PAGE_SIZE,
  createCustomerSchema,
  customerFieldsSchema,
  customerNameSchema,
  toCustomerFormValues,
  toCustomerWritePayload,
  updateCustomerSchema,
  type CreateCustomerInput,
  type CustomerFormValues,
  type CustomerStatFilter,
  type UpdateCustomerInput,
} from "@/lib/validations/customer";

export {
  MAX_PARTY_SIZE,
  MIN_PARTY_SIZE,
  QUEUE_ENTRY_STATUSES,
  QUEUE_ENTRY_STATUS_LABELS,
  QUEUE_EVENT_TYPES,
  QUEUE_STATUSES,
  QUEUE_STATUS_LABELS,
  addCustomerToQueueSchema,
  callNextQueueSchema,
  callQueueEntrySchema,
  cancelQueueEntrySchema,
  completeQueueEntrySchema,
  createQueueSchema,
  noShowQueueEntrySchema,
  partySizeSchema,
  queueFieldsSchema,
  seatQueueEntrySchema,
  skipQueueEntrySchema,
  updateQueueSchema,
  updateQueueStatusSchema,
  type AddCustomerToQueueInput,
  type CreateQueueInput,
  type QueueEntryStatus,
  type QueueFormValues,
  type QueueStatus,
  type SeatQueueEntryInput,
  type UpdateQueueInput,
  type UpdateQueueStatusInput,
} from "@/lib/validations/queue";

export {
  joinPublicQueueFieldsSchema,
  joinPublicQueueSchema,
  publicAccessTokenSchema,
  publicBranchSlugParamsSchema,
  toJoinPublicQueueFormValues,
  type JoinPublicQueueFormValues,
  type JoinPublicQueueInput,
  type PublicBranchSlugParams,
} from "@/lib/validations/public-queue";
